---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - neofetch
        - tmux
        - vim-nox

  - name: Create wallpaper directory
    file:
      path: /usr/share/backgrounds
      state: directory
      mode: '0755'

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    ini_file:
      path: /home/wayne/.config/pcmanfm/LXDE-pi/desktop-items-HDMI-A-2.conf
      section: "*"
      option: wallpaper
      value: "/usr/share/backgrounds/ansible-wallpaper.png"
      owner: wayne
      group: wayne
      backup: true

  - name: set wallpaper position
    ini_file:
      path: /home/wayne/.config/pcmanfm/LXDE-pi/desktop-items-HDMI-A-2.conf
      section: "'*'"
      option: wallpaper_mode
      value: "crop"
      owner: wayne
      group: wayne

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/wayne/.bashrc
      owner: wayne
      group: wayne

  - name: copy .bash_alias file
    copy:
      src: files/bash_aliases
      dest: /home/wayne/.bash_aliases
      owner: wayne
      group: wayne

  - name: copy .bashrc file for root user
    copy:
      src: files/bashrc
      dest: /root/.bashrc
      owner: root
      group: root

  - name: add ansible user
    user:
      name: wynbot
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_wynbot
      dest: /etc/sudoers.d/wynbot 
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: wynbot
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/WynSoftCloud/ansible_desktop.git
